image: python:3.12-bookworm

stages:
  - test # Perform Lint and Format checks on the code

# Always setup poetry
before_script:
  - pip install poetry
  - poetry install

# Linting python code with the Pylance linter
lint:
  stage: test
  script:
    - poetry run poe lint

# Check python format style with Black
format:
  stage: test
  script:
    - poetry run poe format-check

# Check import order with isort
sort-import:
  stage: test
  script:
    - poetry run poe sort-check
